# Generated by Django 5.1.7 on 2025-03-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='curl_preparation',
            field=models.TextField(blank=True, help_text='每行一个Curl命令，按顺序执行', verbose_name='CURL准备命令'),
        ),
    ]
