# Generated by Django 5.1.7 on 2025-03-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_testcase_curl_preparation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='date_input',
            field=models.DateField(blank=True, null=True, verbose_name='日期输入'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='timestamp_output',
            field=models.CharField(blank=True, max_length=20, verbose_name='时间戳输出'),
        ),
    ]
